
import type { Timestamp } from 'firebase/firestore';

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  imageUrl: string;
  imageHint: string;
  stock: number;
  rating?: number;
  reviews?: number;
  createdAt: Timestamp; // Changed to non-optional, will be set by server
  updatedAt: Timestamp; // Changed to non-optional, will be set by server
}

export interface CartItem extends Product {
  quantity: number;
}

export interface User {
  id: string; // Firebase UID
  email: string | null; // Firebase email can be null
  name?: string;
  role: 'user' | 'admin';
  createdAt: Timestamp; // Changed to non-optional
  updatedAt?: Timestamp; // Optional for now
}

// Type for new product data, excluding fields generated by the system (id, rating, reviews, timestamps)
export type NewProduct = Omit<Product, 'id' | 'rating' | 'reviews' | 'createdAt' | 'updatedAt'>;

export interface ShippingAddress {
  fullName: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  postalCode: string;
  country: string;
  phoneNumber?: string;
}

